### ISSUE TITLE
i got banned

### ISSUE THREAD

**Issue by Shelford21** [Megant88/Fast-Valorant-Triggerbot#8]
i didnt use the vmp , forgot about it.  i tested it , the triggerbot worked. and in 1 minute, i close the game , exit the vanguard. restart my laptop (just to make sure i dont get ban) . but then yea , i got hwid ban. van 152. (purely my fault)

so out of curiosity , do you use it on vmp and its undetectable? how long have you been using this triggerbot,,

**Comment by Shelford21** [comment]
and i didnt recompile it , i just use the same exe . my fault. don't do the same mistakes i did.

**Comment by dipbd1** [comment]
i used it for few games, didn't compiled it, but after few usage it stopped working.
